import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    'services-attachments-node': 'src/services/attachments/node/local-attachment-store.ts',
    'services-attachments-api': 'src/services/attachments/api/index.ts',
    'primitives-path-api': 'src/primitives/path/api/index.ts',
    'primitives-host-api': 'src/primitives/host/api/index.ts',
    'primitives-git-credentials-api': 'src/primitives/git-credentials/api/index.ts',
    'primitives-exclusion-policy-api': 'src/primitives/exclusion-policy/api/index.ts',
    'primitives-skills-api': 'src/primitives/skills/api/index.ts',
    'primitives-mcp-api': 'src/primitives/mcp/api/index.ts',
    'primitives-exec-api': 'src/primitives/exec/api/index.ts',
    'primitives-host-dependencies-api': 'src/primitives/host-dependencies/api/index.ts',
    'primitives-kv-api': 'src/primitives/kv/api/index.ts',
    'primitives-terminal-shell-api': 'src/primitives/terminal-shell/api/index.ts',
    'primitives-kv-node': 'src/primitives/kv/node/index.ts',
    'primitives-emdash-config-api': 'src/primitives/emdash-config/api/index.ts',
    'primitives-versioned-schema-api': 'src/primitives/versioned-schema/api/index.ts',
    'primitives-runtime-resolution-api': 'src/primitives/runtime-resolution/api/index.ts',
    'primitives-sqlite-store-api': 'src/primitives/sqlite-store/api/index.ts',
    'primitives-sqlite-store-codegen': 'src/primitives/sqlite-store/codegen/index.ts',
    'primitives-sqlite-store-node': 'src/primitives/sqlite-store/node/index.ts',
    'services-exec-api': 'src/services/exec/api/index.ts',
    'services-shell-env-api': 'src/services/shell-env/api/index.ts',
    'services-shell-env-node': 'src/services/shell-env/node/index.ts',
    'services-pty-api': 'src/services/pty/api/index.ts',
    'services-host-dependencies-api': 'src/services/host-dependencies/api/index.ts',
    'services-host-dependencies-node': 'src/services/host-dependencies/node/index.ts',
    'services-runtime-broker-api': 'src/services/runtime-broker/api/index.ts',
    'services-agent-plugins-api-plugins': 'src/services/agent-plugins/api/plugins/index.ts',
    'services-agent-plugins-api-plugins-helpers':
      'src/services/agent-plugins/api/plugins/helpers/index.ts',
    'services-agent-plugins-api-plugins-capabilities-auth':
      'src/services/agent-plugins/api/plugins/capabilities/auth.ts',
    'services-session-intents-api': 'src/services/session-intents/api/index.ts',
    'services-session-intents-node': 'src/services/session-intents/node/index.ts',
    'services-fs-watch-api': 'src/services/fs-watch/api/index.ts',
    'services-fs-watch-node': 'src/services/fs-watch/node/index.ts',
    'runtimes-git-api': 'src/runtimes/git/api/index.ts',
    'runtimes-git-node': 'src/runtimes/git/node/index.ts',
    'runtimes-files-api': 'src/runtimes/files/api/index.ts',
    'runtimes-files-node': 'src/runtimes/files/node/index.ts',
    'runtimes-file-search-api': 'src/runtimes/file-search/api/index.ts',
    'runtimes-file-search-node': 'src/runtimes/file-search/node/index.ts',
    'runtimes-acp-api': 'src/runtimes/acp/api/index.ts',
    'runtimes-acp-api-client': 'src/runtimes/acp/api/client.ts',
    'runtimes-acp-api-transport': 'src/runtimes/acp/api/transport.ts',
    'runtimes-acp-node': 'src/runtimes/acp/node/index.ts',
    'runtimes-agent-config-api': 'src/runtimes/agent-config/api/index.ts',
    'runtimes-agent-config-node': 'src/runtimes/agent-config/node/index.ts',
    'runtimes-automations-api': 'src/runtimes/automations/api/index.ts',
    'runtimes-automations-node': 'src/runtimes/automations/node/index.ts',
    'runtimes-conversations-api': 'src/runtimes/conversations/api/index.ts',
    'runtimes-conversations-node': 'src/runtimes/conversations/node/index.ts',
    'runtimes-tui-agents-api': 'src/runtimes/tui-agents/api/index.ts',
    'runtimes-tui-agents-node': 'src/runtimes/tui-agents/node/index.ts',
    'runtimes-terminals-api': 'src/runtimes/terminals/api/index.ts',
    'runtimes-terminals-node': 'src/runtimes/terminals/node/index.ts',
    'runtimes-workspace-registry-api': 'src/runtimes/workspace-registry/api/index.ts',
    'runtimes-workspace-registry-node': 'src/runtimes/workspace-registry/node/index.ts',
    'runtimes-resource-usage-api': 'src/runtimes/resource-usage/api/index.ts',
    'runtimes-resource-usage-node': 'src/runtimes/resource-usage/node/index.ts',
    'runtimes-host-settings-api': 'src/runtimes/host-settings/api/index.ts',
    'runtimes-host-settings-node': 'src/runtimes/host-settings/node/index.ts',
    'runtimes-scripts-api': 'src/runtimes/scripts/api/index.ts',
    'runtimes-scripts-node': 'src/runtimes/scripts/node/index.ts',
    'services-preview-detection-api': 'src/services/preview-detection/api/index.ts',
    'workspace-server': 'src/workspace-server/index.ts',
  },
  format: ['esm'],
  dts: true,
  deps: {
    // Package subpath imports (#runtimes/*, ...) point at package-internal src
    // and must be bundled; dist output has to stay self-contained.
    alwaysBundle: [/^#/],
    neverBundle: [
      '@agentclientprotocol/sdk',
      '@emdash/shared',
      '@emdash/wire',
      '@parcel/watcher',
      'drizzle-kit',
      'glob',
      'minimatch',
      'node-pty',
      'react',
      'semver',
      'smol-toml',
      'zod',
    ],
  },
  sourcemap: true,
  clean: true,
});
